

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  tagName: '$(Build.BuildNumber)'
  imageName: '$(dockerid)/codepiefe:$(tagName)'

jobs:
  - job: prepare_published_files
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - script: docker build -f Dockerfile -t $(imageName) .
        displayName: 'Docker build'

      - script: |
          docker login -u $(dockerid) -p $(password)
          docker push $(imageName)
        displayName: 'Push docker image'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish temp files'
        inputs:
          PathtoPublish: 'docker-compose.yml'
          ArtifactName: 'drop'
          publishLocation: 'Container'