// common
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

// auth
export const SET_USER = 'SET_USER'

// checkout
export const SET_CURRENTSTEP = 'SET_CURRENTSTEP'
export const SET_CHECKOUTDATA = 'SET_CHECKOUTDATA'
export const SET_CURRENTORDERID = 'SET_CURRENTORDERID'
export const ADD_VALIDATEDSTEP = 'ADD_VALIDATEDSTEP'
export const REMOVE_VALIDATEDSTEP = 'REMOVE_VALIDATEDSTEP'
export const SET_VALIDATEDSTEP = 'SET_VALIDATEDSTEP'

// virto
export const SET_VIRTO_CATEGORIES = 'SET_VIRTO_CATEGORIES'
export const SET_VIRTO_PRODUCTS = 'SET_VIRTO_PRODUCTS'
export const SET_ISALLPRODUCTSSEARCHED = 'SET_ISALLPRODUCTSSEARCHED'
export const SET_MULTIVALUE_ISALLPRODUCTSSEARCHED = 'SET_MULTIVALUE_ISALLPRODUCTSSEARCHED'

// contract
export const SET_CONTRACTDATA = 'SET_CONTRACTDATA'

// settings
export const SET_SETTINGS = 'SET_SETTINGS'
